[package]
name = "rusky"
version = "0.2.1"
edition = "2021"
authors = ["xhwhis <hi@whis.me>"]
description = "ğŸ¦€ + ğŸ¶ = Rusky (rusty husky). Modern native git hooks made easy. No dependencies."
repository = "https://github.com/xhwhis/rusky"
license = "Unlicense"

[dev-dependencies]
rusky = "0.2.1"
